export class internship {
    _id?:any;
    firstName?:string;
    lastName?:string;
    Email?:string;
    tel?:string;
    birthday?:string;
    adresse?:string;
    profilLinkedin?:string;
    levelOfStudy?:string;
    University?:string;
    Subsidiary?:string;
    competences?:string;
    certifcats?:string;
    internshipDuration?:string;
    startDate?:string;
    endDate?:string;
    file?:string;
    decision?:string;
}